name: CI Pipeline  # Name of the workflow

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Runs when a PR is opened to main

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # The OS the job will run on

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checks out your repo so the workflow can access the files

      - name: Set Up Node.js
        uses: actions/setup-node@v3  # Sets up Node.js environment
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install  # Installs project dependencies

      - name: Run Tests
        run: npm test  # Runs tests (if defined in your project)
